import jsPDF from 'jspdf';

interface ReportData {
  type: string;
  items: any[];
  sales: any[];
  generatedAt: string;
}

export const generatePDFReport = async (data: ReportData): Promise<Blob> => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let yPosition = 20;

  // Header
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Stock Manager Report', pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 10;
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Generated: ${new Date(data.generatedAt).toLocaleString()}`, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 15;
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  
  const reportTitle = getReportTitle(data.type);
  pdf.text(reportTitle, 20, yPosition);
  yPosition += 15;

  // Generate content based on report type
  switch (data.type) {
    case 'stock-summary':
      yPosition = generateStockSummary(pdf, data, yPosition, pageHeight);
      break;
    case 'low-stock':
      yPosition = generateLowStockReport(pdf, data, yPosition, pageHeight);
      break;
    case 'sales-report':
      yPosition = generateSalesReport(pdf, data, yPosition, pageHeight);
      break;
    case 'complete-inventory':
      yPosition = generateCompleteInventory(pdf, data, yPosition, pageHeight);
      break;
  }

  // Footer
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Page ${i} of ${totalPages}`, pageWidth - 30, pageHeight - 10, { align: 'right' });
    pdf.text('Generated by Stock Manager', 20, pageHeight - 10);
  }

  return pdf.output('blob');
};

const getReportTitle = (type: string): string => {
  const titles = {
    'stock-summary': 'Stock Summary Report',
    'low-stock': 'Low Stock Alert Report',
    'sales-report': 'Sales Performance Report',
    'complete-inventory': 'Complete Inventory Report',
  };
  return titles[type as keyof typeof titles] || 'Stock Report';
};

const generateStockSummary = (pdf: jsPDF, data: ReportData, yPos: number, pageHeight: number): number => {
  let yPosition = yPos;
  
  // Summary statistics
  const lowStockItems = data.items.filter(item => item.quantity < item.minQuantity);
  const categories = [...new Set(data.items.map(item => item.category))];
  const totalSales = data.sales.reduce((sum, sale) => sum + sale.quantitySold, 0);
  const totalRevenue = data.sales.reduce((sum, sale) => sum + (sale.totalPrice || 0), 0);

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Summary Statistics:', 20, yPosition);
  yPosition += 10;

  pdf.setFont('helvetica', 'normal');
  pdf.text(`Total Items: ${data.items.length}`, 30, yPosition);
  yPosition += 7;
  pdf.text(`Low Stock Items: ${lowStockItems.length}`, 30, yPosition);
  yPosition += 7;
  pdf.text(`Categories: ${categories.length}`, 30, yPosition);
  yPosition += 7;
  pdf.text(`Total Sales: ${totalSales} units`, 30, yPosition);
  yPosition += 7;
  if (totalRevenue > 0) {
    pdf.text(`Total Revenue: Rs. ${totalRevenue.toFixed(2)}`, 30, yPosition);
    yPosition += 7;
  }
  yPosition += 8;

  // Low stock alerts
  if (lowStockItems.length > 0) {
    pdf.setFont('helvetica', 'bold');
    pdf.text('Low Stock Alerts:', 20, yPosition);
    yPosition += 10;

    lowStockItems.forEach(item => {
      if (yPosition > pageHeight - 30) {
        pdf.addPage();
        yPosition = 20;
      }
      
      pdf.setFont('helvetica', 'normal');
      pdf.text(`• ${item.name} (${item.brand}) - ${item.quantity} remaining (Min: ${item.minQuantity})`, 30, yPosition);
      yPosition += 7;
    });
  }

  return yPosition;
};

const generateLowStockReport = (pdf: jsPDF, data: ReportData, yPos: number, pageHeight: number): number => {
  let yPosition = yPos;
  const lowStockItems = data.items.filter(item => item.quantity < item.minQuantity);

  if (lowStockItems.length === 0) {
    pdf.setFontSize(12);
    pdf.text('No items are currently low in stock.', 20, yPosition);
    return yPosition + 20;
  }

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`${lowStockItems.length} items require immediate attention:`, 20, yPosition);
  yPosition += 15;

  lowStockItems.forEach((item, index) => {
    if (yPosition > pageHeight - 40) {
      pdf.addPage();
      yPosition = 20;
    }

    pdf.setFont('helvetica', 'bold');
    pdf.text(`${index + 1}. ${item.name}`, 20, yPosition);
    yPosition += 7;
    
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Brand: ${item.brand}`, 30, yPosition);
    yPosition += 5;
    pdf.text(`Category: ${item.category}`, 30, yPosition);
    yPosition += 5;
    pdf.text(`Current Stock: ${item.quantity} units`, 30, yPosition);
    yPosition += 5;
    pdf.text(`Minimum Required: ${item.minQuantity} units`, 30, yPosition);
    yPosition += 5;
    pdf.text(`Shortage: ${Math.max(0, item.minQuantity - item.quantity)} units`, 30, yPosition);
    yPosition += 10;
  });

  return yPosition;
};

const generateSalesReport = (pdf: jsPDF, data: ReportData, yPos: number, pageHeight: number): number => {
  let yPosition = yPos;
  
  // Sales summary
  const totalSales = data.sales.reduce((sum, sale) => sum + sale.quantitySold, 0);
  const totalTransactions = data.sales.length;
  const totalRevenue = data.sales.reduce((sum, sale) => sum + (sale.totalPrice || 0), 0);
  
  // Today's sales
  const today = new Date();
  const todaySales = data.sales.filter(sale => {
    const saleDate = new Date(sale.saleDate);
    return saleDate.toDateString() === today.toDateString();
  });
  const todayTotal = todaySales.reduce((sum, sale) => sum + sale.quantitySold, 0);
  const todayRevenue = todaySales.reduce((sum, sale) => sum + (sale.totalPrice || 0), 0);

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Sales Summary:', 20, yPosition);
  yPosition += 10;

  pdf.setFont('helvetica', 'normal');
  pdf.text(`Total Sales: ${totalSales} units`, 30, yPosition);
  yPosition += 7;
  pdf.text(`Total Transactions: ${totalTransactions}`, 30, yPosition);
  yPosition += 7;
  if (totalRevenue > 0) {
    pdf.text(`Total Revenue: Rs. ${totalRevenue.toFixed(2)}`, 30, yPosition);
    yPosition += 7;
  }
  pdf.text(`Today's Sales: ${todayTotal} units`, 30, yPosition);
  yPosition += 7;
  if (todayRevenue > 0) {
    pdf.text(`Today's Revenue: Rs. ${todayRevenue.toFixed(2)}`, 30, yPosition);
    yPosition += 7;
  }
  yPosition += 8;

  // Recent sales
  pdf.setFont('helvetica', 'bold');
  pdf.text('Recent Sales (Last 10):', 20, yPosition);
  yPosition += 10;

  const recentSales = data.sales.slice(0, 10);
  recentSales.forEach(sale => {
    if (yPosition > pageHeight - 30) {
      pdf.addPage();
      yPosition = 20;
    }
    
    pdf.setFont('helvetica', 'normal');
    const saleDate = new Date(sale.saleDate).toLocaleDateString();
    const priceInfo = sale.totalPrice ? ` - Rs. ${sale.totalPrice.toFixed(2)}` : '';
    pdf.text(`• ${sale.itemName} - ${sale.quantitySold} units (${saleDate})${priceInfo}`, 30, yPosition);
    yPosition += 7;
  });

  return yPosition;
};

const generateCompleteInventory = (pdf: jsPDF, data: ReportData, yPos: number, pageHeight: number): number => {
  let yPosition = yPos;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`Complete Inventory (${data.items.length} items):`, 20, yPosition);
  yPosition += 15;

  data.items.forEach((item, index) => {
    if (yPosition > pageHeight - 50) {
      pdf.addPage();
      yPosition = 20;
    }

    pdf.setFont('helvetica', 'bold');
    pdf.text(`${index + 1}. ${item.name}`, 20, yPosition);
    yPosition += 7;
    
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Brand: ${item.brand}`, 30, yPosition);
    yPosition += 5;
    pdf.text(`Category: ${item.category}`, 30, yPosition);
    yPosition += 5;
    pdf.text(`Quantity: ${item.quantity} units`, 30, yPosition);
    yPosition += 5;
    pdf.text(`Min Quantity: ${item.minQuantity} units`, 30, yPosition);
    yPosition += 5;
    
    if (item.description) {
      pdf.text(`Description: ${item.description}`, 30, yPosition);
      yPosition += 5;
    }
    
    const status = item.quantity < item.minQuantity ? 'LOW STOCK' : 
                   item.quantity === 0 ? 'OUT OF STOCK' : 'IN STOCK';
    pdf.text(`Status: ${status}`, 30, yPosition);
    yPosition += 10;
  });

  return yPosition;
};

// Google Drive integration - Updated to handle demo environment limitations
export const initializeGoogleDrive = async (): Promise<boolean> => {
  try {
    // Since this is a demo environment without proper Google API credentials,
    // we'll return false to indicate connection is not available
    console.log('Google Drive integration attempted in demo environment...');
    
    // Simulate a delay to show the connection process
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    // Always return false for demo environment
    return false;
  } catch (error) {
    console.error('Google Drive initialization error:', error);
    return false;
  }
};

export const uploadToGoogleDrive = async (pdfBlob: Blob, reportType: string): Promise<string | null> => {
  try {
    // Log the attempt for debugging
    console.log(`Google Drive upload attempted for: ${reportType}-${new Date().toISOString().split('T')[0]}.pdf`);
    console.log('PDF Blob size:', pdfBlob.size, 'bytes');
    
    // Since Google Drive integration requires proper OAuth setup,
    // we'll return null to trigger local download instead
    return null;
  } catch (error) {
    console.error('Upload error:', error);
    return null;
  }
};